version: '3.9'

services:
  handler:
    container_name: handler
    build:
      context: /handler
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - PSQL_HOST=db
      - PSQL_USER=postgres
      - PSQL_PASSWORD=eldoseldos
      - PSQL_DB=exchange_api
    depends_on:
      - handler_db
    ports:
      - "8080:8080"

  handler_db:
    container_name: handler_psql
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eldoseldos
      POSTGRES_DB: exchange_api
    volumes:
      - /handler/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    restart: always

